In [150]:
import google.generativeai as genai
import time
import pandas as pd

In [151]:
# Configuring API key
genai.configure(api_key='AIzaSyC_vMdI3JNPIAqexqpaKUXgl9wZrLtg9KA')

In [152]:
for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

models/gemini-1.0-pro
models/gemini-1.0-pro-001
models/gemini-1.0-pro-latest
models/gemini-1.0-pro-vision-latest
models/gemini-pro
models/gemini-pro-vision

In [153]:
model = genai.GenerativeModel('gemini-pro')

In [154]:
perguntas = [
    'olá, como são formadas as cavernas? e as estalactites e estalagmites?',
    'Qual a diferença entre a gordura animal e a gordura vegetal hidrogenada?',
    'Como funciona a relação do ângulo externo do triângulo com os outros dois ângulos internos do triângulo?',
    '(UESB BA/2017) Sejam dois conjuntos não vazios,' + '\n' + 
    'quaisquer, X e Y, satisfazendo a seguinte propriedade:' + '\n' +
    '“A quantidade de subconjuntos de X é o dobro da' + '\n' +
    'quantidade de subconjuntos de Y”.' + '\n' +
    'Considerando-se n (X) o número de elementos do' + '\n' +
    'conjunto X, e n (Y), o número de elementos do conjunto' + '\n' +
    'Y, é correto afirmar que n (X) é igual a' + '\n' +
    '01. n (Y) + 4.' + '\n' +
    '02. n (Y) + 2.' + '\n' +
    '03. n (Y) + 1.' + '\n' +
    '04. 2n (Y).' + '\n' +
    '05. 4n (Y).',
    'Boa tarde! Qual a relação das mitocôndrias com a síntese proteica?',
    'Entre as consequências da Expansão Marítima,' + '\n' +
    'não encontramos a)' + '\n' +
    'a formação do Sistema Colonial.' + '\n' +
    'b) o desenvolvimento do eurocentrismo.' + '\n' +
    'c) a expansão do regime assalariado da Europa para a' + '\n' +
    'América.' + '\n' +
    'd) início do processo de acumulação de capitais.' + '\n' +
    'impulsionando o modo de produção capitalista.' + '\n' +
    'e) introdução do trabalho escravo na América.',
    'Ainda não entendi o que significa eu Lírico, pode me explicar?',
    'Quanto vale 18 rad?',
    'Se {-1; 2x+y; 2; 3; 1} = {2; 4; x-y; 1; 3}, então ' + '\n' +
    'a) x>y' + '\n' +
    'b) x<y' + '\n' +
    'c) x=y' + '\n' +
    'd) 2x<y' + '\n' +
    'e) x> 2y',
    'Olá, todos os conceitos de potencial (potencial gravitacional, potencial elétrico, etc) utilizam noções de trabalho? Por quê?'
]

In [155]:
respostas = [
    'Química',
    'Biologia',
    'Matemática',
    'Matemática',
    'Biologia',
    'História',
    'Literatura',
    'Matemática',
    'Matemática',
    'Física',
]

Diferentes maneiras de formular a pergunta

In [156]:
formatos_de_perguntas = {
    'F1': 'Responda qual matéria corresponde à seguinte pergunta? {}. Escolha entre Português, Literatura, Redação, Biologia, Geografia, Matemática, Física, História, Química, Inglês, Espanhol, Filosofia, Sociologia, História da Arte, Orientação de Estudos e Ensino Religioso.',
    'F2': 'Responda qual matéria entre Português, Literatura, Redação, Biologia, Geografia, Matemática, Física, História, Química, Inglês, Espanhol, Filosofia, Sociologia, História da Arte, Orientação de Estudos e Ensino Religioso corresponde à seguinte pergunta? {}.',
    'F3': 'Qual matéria corresponde à seguinte pergunta? {}. Escolha entre Português, Literatura, Redação, Biologia, Geografia, Matemática, Física, História, Química, Inglês, Espanhol, Filosofia, Sociologia, História da Arte, Orientação de Estudos e Ensino Religioso.',
}

In [157]:
rows = []
for pergunta, resposta in zip(perguntas, respostas):
    for formato in formatos_de_perguntas:
        pergunta = formatos_de_perguntas[formato].format(pergunta)
        start_time = time.time()
        response = model.generate_content(f"Responda qual matéria corresponde à seguinte pergunta? {pergunta}")
        end_time = time.time()
        row = {
            'formato': formato,
            'tempo(s)': end_time - start_time,
            'resposta': response.text,
            'resposta_correta': resposta,
        }
        rows.append(row)
df = pd.DataFrame(rows)

In [158]:
df

,formato,tempo(s),resposta,resposta_correta
0,F1,3.982213,Geografia,Química
1,F2,1.938760,Geografia,Química
2,F3,1.329080,Geografia,Química
3,F1,5.880631,Química,Biologia
4,F2,1.270403,Química,Biologia
5,F3,1.050501,Química,Biologia
6,F1,1.022788,Matemática,Matemática
7,F2,5.131952,Matemática,Matemática
8,F3,0.909758,Matemática,Matemática
9,F1,1.331653,Matemática,Matemática
10,F2,1.065234,Matemática,Matemática
11,F3,2.202109,.,Matemática
12,F1,1.039489,Biologia,Biologia
13,F2,1.976839,segue,Biologia
14,F3,1.312819,Biologia,Biologia
15,F1,2.411778,"Deixe, diga, diga, diga, diga, diga, diga, di...",História
16,F2,1.185671,História,História
17,F3,3.285654,História,História
18,F1,1.972162,Literatura,Literatura
19,F2,1.085046,Literatura,Literatura
20,F3,0.933651,Literatura,Literatura
21,F1,1.018440,Matem Física,Matemática
22,F2,1.032166,Matemática,Matemática
23,F3,0.977853,Matemática,Matemática
24,F1,1.010019,Matemática,Matemática
25,F2,1.505877,"sympy,᷄ Cocoa",Matemática
26,F3,0.906352,**Matemática**,Matemática
27,F1,1.205480,Física,Física
28,F2,0.928217,Física,Física
29,F3,1.290160,Física,Física

In [159]:
df['acertou'] = df['resposta'] == df['resposta_correta']
df.pivot_table(index='formato', values='acertou', aggfunc='mean')

         acertou
formato
F1           0.6
F2           0.6
F3           0.5

O primeiro formato de pergunta acerta 80% das vezes

No futuro, existe a possibilidade de melhorar a resposta estudando algumas propriedades da resposta

In [160]:
response.prompt_feedback

safety_ratings {
  category: HARM_CATEGORY_SEXUALLY_EXPLICIT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HATE_SPEECH
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HARASSMENT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_DANGEROUS_CONTENT
  probability: NEGLIGIBLE
}

## Desenho da pesquisa

Ao começar o projeto primeiro é necessário entender o problema e os dados disponíveis.
O problema é multiobjetivo: melhorar as variáveis
 - V1: Taxa de acerto (Mais importante)
 - V2: Custo
 - V3: Velocidade da resposta
Então o objetivo deveria ter um peso maior (0.6) para V1 e pesos menores (0.2) para V2 e V3.

Dúvidas:
- O que representa o custo exatamente? falsos positivos no modelo? contratar um plano de um modelo LLM como Gemini pro, por exemplo?
- Quais são as expectativas realistas que a empresa tem sobre o projeto?

O objetivo final é ter um modelo LLM que classifique o texto recebido em uma das categorias existentes.

Para conseguir esse objetivo, primeiro devem ser analisados os dados disponíveis e construir um dataset balanceado de treino, validação e test.

Depois, o baseline.
No caso a empresa tenha um modelo pronto, esse formaria o baseline. Mas, se não tiver, poderia ser escolhido algum dos modelos gratuitos da internet, previa reunião.

A função objetivo já foi definida no começo. A tarefa se torna um problema de otimização considerando:
- modelo
- promt da pergunta
Por exemplo, os formatos mostrados no começo presentam como o promt é importante, derivando em melhores ou piores respostas.

O processo deve ser iterativo, balanceando as importancias de cada um dos objetivos (acurácia, custo, tempo) e modelar assim qual combinação fica melhor. A curva pareto pode ajudar para esse fim.